### ISSUE TITLE
¡Enhorabuena Ingeniera! 😀️

### ISSUE THREAD

**Issue by Obijuan** [Elenadr/MyVectorscope#1]
Te abro esta issue para que la cierres cuando leas el TFG y seas Ingeniera (con mayúsculas!)  
¡Muy buen trabajo!
Y muchísimas gracias por publicarlo y compartirlo con el mundo 😉️

**Comment by Obijuan** [comment]
Obijuan approved!  
![Obijuan-approved](https://user-images.githubusercontent.com/1286062/233062490-77d05e34-39d4-4ff1-9911-5f50f2856a53.jpg)

**Comment by Obijuan** [comment]
Enhorabuena Ingeniera! Ya puedes cerrar está issue. ¡Completada!
Para el recuerdo:
![Ingeniera-Elena-Hermione](https://user-images.githubusercontent.com/1286062/233083060-0e879154-4f14-4c36-9416-818874f19aa2.jpg)

**Comment by Elenadr** [comment]
¡Muchísimas gracias Obijuan, por todo! :) 
¡Travesura realizada!
